version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "ccamel"
    reviewers:
      - "ccamel"

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "ccamel"
    reviewers:
      - "ccamel"
