version: "3.8"
services:
  postgres:
    image: bitnami/postgresql:17.5.0
    container_name: postgres
    restart: always
    ports:
      - "55432:5432"
    env_file:
      - .env
    volumes:
      - ${dsm_volume_docker}/postgres/data:/var/lib/postgresql/data
    networks:
      - app_shared

  adminer:
    image: adminer:5.3.0
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - app_shared

networks:
  app_shared:
    driver: bridge
