name: Build

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install Just
        uses: extractions/setup-just@v3
        with:
          just-version: '1.42.4'

      - name: Terraform Init
        run: just init

      - name: Terraform Plan
        run: just plan
        env:
          TF_VAR_dsm_host: ${{ secrets.DSM_HOST }}
          TF_VAR_dsm_user: ${{ secrets.DSM_USER }}
          TF_VAR_dsm_password: ${{ secrets.DSM_PASSWORD }}
