name: Lint

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-commits:
    runs-on: ubuntu-22.04
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check commits
        uses: wagoid/commitlint-github-action@v6

  lint-markdown:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Lint markdown files
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          args: "**/*.md"

  lint-yaml:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Lint yaml files
        uses: ibiqlik/action-yamllint@v3.1.1

  validate-terraform:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Find changed terraform files
        id: changed-tf-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            **/*.tf
            **/*.tfvars
            **/*.hcl

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        if: steps.changed-tf-files.outputs.any_changed == 'true'
        with:
          terraform_wrapper: false

      - name: Install Just
        uses: extractions/setup-just@v3
        with:
          just-version: '1.42.4'

      - name: Validate Terraform files
        if: steps.changed-tf-files.outputs.any_changed == 'true'
        run: |
          just init
          just validate

      - name: Check Terraform files format
        if: steps.changed-tf-files.outputs.any_changed == 'true'
        run: |
          just check-fmt
